import type { Metadata } from "next";
import { Toaster } from "sonner";
import { NuqsAdapter } from "nuqs/adapters/next/app";

import TanstackProvider from "@/context/tanstack-context";
import { sfProDisplay } from "@/assets/fonts";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${sfProDisplay.className} antialiased`}>
        <TanstackProvider>
          <NuqsAdapter>{children}</NuqsAdapter>
        </TanstackProvider>
        <Toaster richColors position="top-right" />
      </body>
    </html>
  );
}
